-- Natural Language: Explain this query for business users
-- Generated by Llama 3.1 via Groq

**Query Explanation**

This query is used to calculate the total amount spent by each customer from the "orders" table. Here's a breakdown of what the query does:

**SELECT**
- This keyword is used to select the columns we want to retrieve from the database. In this case, we're selecting two columns:
  - `customer_id`: This is a unique identifier for each customer.
  - `SUM(amount)`: This calculates the total amount spent by each customer.

**FROM orders**
- This specifies the table from which we want to retrieve data. In this case, it's the "orders" table.

**GROUP BY customer_id**
- This groups the results by the `customer_id`. Essentially, it groups all the orders made by each customer together, so we can calculate the total amount spent by each customer.

**What the query does:**

When you run this query, it will return a list of customers, along with the total amount they spent. For example:

| customer_id | SUM(amount)  |
|-------------|--------------|
| 123         | 100.00       |
| 456         | 200.00       |
| 789         | 50.00        |

This means:

- Customer with ID 123 spent a total of $100.00.
- Customer with ID 456 spent a total of $200.00.
- Customer with ID 789 spent a total of $50.00.

**Use case:**

This query can be useful for business users who want to:

- Analyze customer spending habits
- Identify top-spending customers
- Track customer lifetime value
- Make informed decisions about marketing and sales strategies