# Auto-generated by pyspark_codegen.py via Llama 3.1

# Import PySpark libraries
from pyspark.sql import SparkSession
from pyspark.sql import functions as F

# Initialize Spark Session
spark = SparkSession.builder.appName("Total Revenue Analysis").getOrCreate()

# Load the Orders CSV into a Spark DataFrame
orders_df = spark.read.option("inferSchema", "true").csv(
    "path_to_orders_csv")
# Assuming CSV path is stored in a variable named orders_csv_path

# Convert the 'order_date' column to date type (if necessary)
orders_df = orders_df.withColumn("order_date", F.col("order_date").cast("date"))

# Calculate total revenue by summing the 'amount' column
total_revenue_df = orders_df.groupBy().sum("amount").withColumnRenamed("sum(amount)", "total_revenue")

# Print total revenue
total_revenue_df.show()

# Calculate total revenue grouped by product_name (join with Products)
# Join the Orders table with the Products table on product_id
product_revenue_df = orders_df.join(spark.read.csv("path_to_products_csv", 
    schema={"product_id": "integer", "product_name": "string", "category": "string"}, 
    header=True, inferSchema=True).withColumnRenamed("product_id", "product_id_key"), 
    on="product_id")

# Group by product_name and sum the 'amount' column
product_revenue_df = product_revenue_df.groupBy("product_name").sum("amount")

# Create a new column for total revenue grouped by product_name
product_revenue_df = product_revenue_df.withColumnRenamed("sum(amount)", "total_revenue_product").withColumnRenamed("product_name", "product_name_key")

# Select only the 'product_name_key' and 'total_revenue_product' columns
product_revenue_df = product_revenue_df.select("product_name_key", "total_revenue_product")

# Join with the Products table to get product_name
product_revenue_df = product_revenue_df.join(spark.read.csv("path_to_products_csv", 
    schema={"product_id": "integer", "product_name": "string", "category": "string"},
    header=True, inferSchema=True).withColumnRenamed("product_id", "product_id_key"), 
    on="product_name_key")

# Drop the 'product_name_key' column
product_revenue_df = product_revenue_df.drop("product_name_key")

# Print product revenue
product_revenue_df.show()

# Calculate total revenue grouped by region (join with Customers)
# Join the Orders table with the Customers table on customer_id
customer_revenue_df = orders_df.join(spark.read.csv("path_to_customers_csv", 
    schema={"customer_id": "integer", "name": "string", "region": "string"}, 
    header=True, inferSchema=True), 
    on="customer_id")

# Group by region and sum the 'amount' column
customer_revenue_df = customer_revenue_df.groupBy("region").sum("amount")

# Create a new column for total revenue grouped by region
customer_revenue_df = customer_revenue_df.withColumnRenamed("sum(amount)", "total_revenue_region")

# Print customer revenue
customer_revenue_df.show()