# nl_to_sql.py — converts natural language queries into SQL using Llama via Groq
from groq import Groq
import os

client = Groq(api_key=os.environ["GROQ_API_KEY"])

# ── Database schema — tell the model what tables and columns exist ─
schema = """
Database Schema:

Table: orders
  - order_id     INT          (unique order identifier)
  - customer_id  INT          (foreign key → customers)
  - product_id   INT          (foreign key → products)
  - amount       DECIMAL      (revenue for this order)
  - order_date   DATE         (date the order was placed)

Table: customers
  - customer_id  INT          (unique customer identifier)
  - name         VARCHAR      (customer full name)
  - region       VARCHAR      (North / South / East / West)

Table: products
  - product_id   INT          (unique product identifier)
  - product_name VARCHAR      (name of the product)
  - category     VARCHAR      (Electronics / Furniture / etc.)
"""

# ── Natural language query to convert ────────────────────────────
natural_language_query = "Explain this query for business users"

# ── Prompt ────────────────────────────────────────────────────────
prompt = f"""
Convert the following natural language query into a SQL query.

{schema}

Natural Language Query:
"{natural_language_query}"

Rules:
- Use standard SQL syntax (compatible with PostgreSQL / MySQL)
- Use proper JOINs where needed
- Use aliases to keep the query readable
- Add a brief comment above each major clause explaining what it does
- Return ONLY the SQL query — no explanation text outside the query

SQL Query:
"""

print("=" * 60)
print("  🗣️  Natural Language → SQL Converter")
print("=" * 60)
print(f"\n📝 Input  : {natural_language_query}")
print("\n🤖 Generating SQL...\n")

# ── Send to Groq / Llama ──────────────────────────────────────────
response = client.chat.completions.create(
    model="llama-3.1-8b-instant",
    max_tokens=400,
    messages=[
        {
            "role": "system",
            "content": (
                "Schema:" 
                "SELECT customer_id, SUM(amount)"
                "FROM orders"
                "GROUP BY customer_id;"
            )
        },
        {"role": "user", "content": prompt}
    ]
)

# ── Print the generated SQL ───────────────────────────────────────
generated_sql = response.choices[0].message.content.strip()

print("─" * 60)
print(generated_sql)
print("─" * 60)
print(f"\n✅ Tokens used : {response.usage.total_tokens}")

# ── Save to file ──────────────────────────────────────────────────
output_path = os.path.join(os.path.dirname(__file__), "generated_query.sql")
with open(output_path, "w") as f:
    f.write(f"-- Natural Language: {natural_language_query}\n")
    f.write(f"-- Generated by Llama 3.1 via Groq\n\n")
    f.write(generated_sql)

print(f"💾 SQL saved to : generated_query.sql")
print("=" * 60)
