# pyspark_codegen.py — prompts Llama to generate PySpark code for total revenue
from groq import Groq
import os

client = Groq(api_key=os.environ["GROQ_API_KEY"])

# ── Schema context so the model generates accurate column names ───
schema_context = """
We have the following data schema:

Orders table columns: order_id, customer_id, product_id, amount, order_date
Customers table columns: customer_id, name, region
Products table columns: product_id, product_name, category

The 'amount' column in Orders represents the revenue for each order.
"""

# ── The code generation prompt ────────────────────────────────────
prompt = f"""
{schema_context}

Task: Generate PySpark code to calculate total revenue.

Requirements:
1. Read the Orders CSV into a Spark DataFrame
2. Calculate the total revenue by summing the 'amount' column
3. Also calculate total revenue grouped by product_name (join with Products)
4. Also calculate total revenue grouped by region (join with Customers)
5. Display all results using .show()

Provide clean, production-ready PySpark code with comments.
"""

print("=" * 60)
print("  ⚡ PySpark Code Generator — Total Revenue")
print("=" * 60)
print("\n🤖 Asking Llama to generate PySpark code...\n")

# ── Send to Groq / Llama ──────────────────────────────────────────
response = client.chat.completions.create(
    model="llama-3.1-8b-instant",
    max_tokens=800,
    messages=[
        {
            "role": "system",
            "content": (
                "Act as a senior Data Engineer."
                "Generate optimized PySpark code for total revenue.\n"
            )
        },
        {"role": "user", "content": prompt}
    ]
)

# ── Print the generated code ──────────────────────────────────────
generated_code = response.choices[0].message.content
print(generated_code)
print(f"\n✅ Tokens used: {response.usage.total_tokens}")
print("=" * 60)

# ── Optionally save the generated code to a .py file ─────────────
output_path = os.path.join(os.path.dirname(__file__), "generated_pyspark.py")
# Extract only the code block if markdown fences are present
code_to_save = generated_code
if "```python" in code_to_save:
    code_to_save = code_to_save.split("```python")[1].split("```")[0].strip()
elif "```" in code_to_save:
    code_to_save = code_to_save.split("```")[1].split("```")[0].strip()

with open(output_path, "w") as f:
    f.write("# Auto-generated by pyspark_codegen.py via Llama 3.1\n\n")
    f.write(code_to_save)

print(f"\n💾 Generated code saved to: generated_pyspark.py")
