version: 2

models:
  - name: fact_customer_revenue
    columns:
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_customer')
              field: customer_id

      - name: total_revenue
        tests:
          - not_null

      - name: category
        tests:
          - not_null
